(* Public testcase 6 : Raise clause subexpression that raises exception *)

let f = (fn x => raise x) in
let g = (fn x => if (f 9) = 20 then x else 0) in
let test = (fn x => (if x = 3 then raise (g 0) else 10) handle 10 30) in
test 3

(* Output : Unhandled exception #9 *)
